package com.wukongtv.a; class f { void a() { int a;
a=0;// .class public final Lcom/wukongtv/a/f;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field public static final a:[I
a=0;// 
a=0;// .field public static b:Ljava/util/HashMap;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method static constructor <clinit>()V
a=0;//     .locals 1
a=0;// 
a=0;//     const/16 v0, 0xec
a=0;// 
a=0;//     #v0=(PosShort);
a=0;//     new-array v0, v0, [I
a=0;// 
a=0;//     #v0=(Reference,[I);
a=0;//     fill-array-data v0, :array_0
a=0;// 
a=0;//     sput-object v0, Lcom/wukongtv/a/f;->a:[I
a=0;// 
a=0;//     return-void
a=0;// 
a=0;//     :array_0
a=0;//     .array-data 4
a=0;//         0x0
a=0;//         0x1
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0xff
a=0;//         0x0
a=0;//         0x30
a=0;//         0x21
a=0;//         0x30
a=0;//         0x9
a=0;//         0x6
a=0;//         0x5
a=0;//         0x2b
a=0;//         0xe
a=0;//         0x3
a=0;//         0x2
a=0;//         0x1a
a=0;//         0x5
a=0;//         0x0
a=0;//         0x4
a=0;//         0x14
a=0;//     .end array-data
a=0;// .end method
a=0;// 
a=0;// .method public static a()[B
a=0;//     .locals 2
a=0;// 
a=0;//     const-string v0, "QAAAAM9MZXTRxf8Nrf0EMBMYnk2nnCm+Rfl2mFsk+m/vHz2Ut/lBy9+NLNOlloIqJa6b9e/JIdd1iMDln+/qdaqZcz1sQfpWKTVmqg7kgQk8M6iKsXkPeCzEn0MSKtPE3KyxJZ8f7ykui1Upvl3r5f4eDuj5XsuThsA2LuEhVmCp7V2KeFh3u1vRm2XzDrab8lAzA1a7HL8k49jVKH1H8WzY4JMJuhkAtjB3n/N9qVf/9Z5hlF0FHCRjxjk/9ocT/11KAfhESTaWae1BhR2ialEc2W8LdO+pa2i1vFVKtJpzCD91+rj5iIdYfB7kngiAC/tnGxzwHx0d/X3r3yOMslPMNyv5iyHHTobVOBM6tEzQhCdW/vDnflGc7PQIXJm9zpSjAF+15nLCMS49VxV5AgP4qJJelGuTniw/ITKD1CLpuiRxPg49/NA9IbcjcHOwfA30V+d05G2OJfVNRimuqjNUqP1PI1qpH04f1WkuPu8ycJsqghKC1uYxyRxJR6G1OXNSRKc2+poD5nOKU5Sjz5l0uaPk/EfvjIgR7sT/m+SMU67zT6g0i5YfSIIyyiU0MujdY6XKkLE09aA4lmEiSZXrMr6ZGFMb5bRIzevZ3zg34WDF8QW4kjGBSZcoP+YgS+ihhXK6QPEb9u3wQ8KkXj004ZIaaGLvGe057P96nkKyMQbeaiGPOAEAAQA= wukong@wukong\u0000"
a=0;// 
a=0;//     :try_start_0
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     const-string v1, "UTF-8"
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/String;->getBytes(Ljava/lang/String;)[B
a=0;//     :try_end_0
a=0;//     .catch Ljava/io/UnsupportedEncodingException; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     :goto_0
a=0;//     return-object v0
a=0;// 
a=0;//     :catch_0
a=0;//     #v1=(Conflicted);
a=0;//     move-exception v1
a=0;// 
a=0;//     #v1=(Reference,Ljava/io/UnsupportedEncodingException;);
a=0;//     invoke-virtual {v0}, Ljava/lang/String;->getBytes()[B
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
a=0;// 
a=0;// .method public static a([B)[B
a=0;//     .locals 5
a=0;// 
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     :try_start_0
a=0;//     #v1=(Null);
a=0;//     sget-object v0, Lcom/wukongtv/a/f;->b:Ljava/util/HashMap;
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_1
a=0;// 
a=0;//     #v0=(Reference,Ljava/util/HashMap;);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     :try_start_1
a=0;//     invoke-static {}, Lcom/wukongtv/a/f;->b()Ljava/util/HashMap;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     sput-object v0, Lcom/wukongtv/a/f;->b:Ljava/util/HashMap;
a=0;//     :try_end_1
a=0;//     .catch Ljava/security/NoSuchAlgorithmException; {:try_start_1 .. :try_end_1} :catch_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_1 .. :try_end_1} :catch_1
a=0;// 
a=0;//     :cond_0
a=0;//     :try_start_2
a=0;//     sget-object v0, Lcom/wukongtv/a/f;->b:Ljava/util/HashMap;
a=0;// 
a=0;//     const-string v2, "private"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-virtual {v0, v2}, Ljava/util/HashMap;->get(Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Ljava/security/interfaces/RSAPrivateKey;
a=0;// 
a=0;//     sget-object v2, Lcom/wukongtv/a/f;->a:[I
a=0;// 
a=0;//     array-length v2, v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     new-array v3, v2, [B
a=0;// 
a=0;//     #v3=(Reference,[B);
a=0;//     const/4 v2, 0x0
a=0;// 
a=0;//     :goto_0
a=0;//     #v4=(Conflicted);
a=0;//     array-length v4, v3
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     if-ge v2, v4, :cond_1
a=0;// 
a=0;//     sget-object v4, Lcom/wukongtv/a/f;->a:[I
a=0;// 
a=0;//     #v4=(Reference,[I);
a=0;//     aget v4, v4, v2
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     int-to-byte v4, v4
a=0;// 
a=0;//     #v4=(Byte);
a=0;//     aput-byte v4, v3, v2
a=0;// 
a=0;//     add-int/lit8 v2, v2, 0x1
a=0;// 
a=0;//     goto :goto_0
a=0;// 
a=0;//     :catch_0
a=0;//     #v2=(Uninit);v3=(Uninit);v4=(Uninit);
a=0;//     move-exception v0
a=0;// 
a=0;//     move-object v0, v1
a=0;// 
a=0;//     :goto_1
a=0;//     #v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);
a=0;//     return-object v0
a=0;// 
a=0;//     :cond_1
a=0;//     #v2=(Integer);v3=(Reference,[B);v4=(Integer);
a=0;//     const-string v2, "RSA/ECB/NOPADDING"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v2}, Ljavax/crypto/Cipher;->getInstance(Ljava/lang/String;)Ljavax/crypto/Cipher;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     const/4 v4, 0x1
a=0;// 
a=0;//     #v4=(One);
a=0;//     invoke-virtual {v2, v4, v0}, Ljavax/crypto/Cipher;->init(ILjava/security/Key;)V
a=0;// 
a=0;//     invoke-virtual {v2, v3}, Ljavax/crypto/Cipher;->update([B)[B
a=0;// 
a=0;//     invoke-virtual {v2, p0}, Ljavax/crypto/Cipher;->doFinal([B)[B
a=0;//     :try_end_2
a=0;//     .catch Ljava/lang/Exception; {:try_start_2 .. :try_end_2} :catch_1
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     goto :goto_1
a=0;// 
a=0;//     :catch_1
a=0;//     #v0=(Conflicted);v2=(Conflicted);v3=(Conflicted);v4=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Exception;);
a=0;//     sget-object v2, Ljava/lang/System;->err:Ljava/io/PrintStream;
a=0;// 
a=0;//     #v2=(Reference,Ljava/io/PrintStream;);
a=0;//     new-instance v3, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v3=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v4, "signData "
a=0;// 
a=0;//     #v4=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v3, v4}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-virtual {v0}, Ljava/lang/Exception;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v2, v0}, Ljava/io/PrintStream;->println(Ljava/lang/String;)V
a=0;// 
a=0;//     move-object v0, v1
a=0;// 
a=0;//     #v0=(Null);
a=0;//     goto :goto_1
a=0;// .end method
a=0;// 
a=0;// .method private static b()Ljava/util/HashMap;
a=0;//     .locals 5
a=0;// 
a=0;//     new-instance v1, Ljava/util/HashMap;
a=0;// 
a=0;//     #v1=(UninitRef,Ljava/util/HashMap;);
a=0;//     invoke-direct {v1}, Ljava/util/HashMap;-><init>()V
a=0;// 
a=0;//     :try_start_0
a=0;//     #v1=(Reference,Ljava/util/HashMap;);
a=0;//     const-string v0, "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy22wmY1aFihtc7baTfwZ\rSDwH3pPsNamgEMaIzf/2lydF/vVupyBFCQSvswsFea7vbGHDhNk9fxenJDvS1iEM\rAyT/5mJCeXc/VN6yQfgN3yEGCvRiVDfVw8COgDYD9EDoQsEIIOe4sVCziDX6iaU1\rnThVvRP7MAfGBBt01xgX/NkEOJVVzwCKX4Sm3ooj7WxalKos+dbjXdMx4HWgXwfo\rbwnI2zpoKpK5Obvp3OA3Mwd+c+zUlxLhVpfafjU+xdgoBbqVePxcB6AaPi4FZ4bn\rWrok0mSc6H6p3yzKkZht+EFLcHYJjqmlKGz5kZahG4K+Mi81Bsg3a/U6LHkuXdzi\rVwIDAQAB\r"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     const-string v2, "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHIYv5KzfMU7KM\rI9/rff0dHR/wHBtn+wuACJ7kHnxYh4j5uPp1PwhzmrRKVby1aGup73QLb9kcUWqi\rHYVB7WmWNklE+AFKXf8Th/Y/OcZjJBwFXZRhnvX/V6l98593MLYAGboJk+DYbPFH\rfSjV2OMkvxy7VgMzUPKbtg7zZZvRW7t3WHiKXe2pYFYh4S42wIaTy1756A4e/uXr\rXb4pVYsuKe8fnyWxrNzE0yoSQ5/ELHgPebGKqDM8CYHkDqpmNSlW+kFsPXOZqnXq\r75/lwIh11yHJ7/WbriUqgpal0yyN38tB+beUPR/vb/okW5h2+UW+KZynTZ4YEzAE\r/a0N/8XRAgMBAAECggEBAL8zX+JE9BO2Pdc/zw6f73yX7YWwh0QlEdrC7EXfW8fp\rg8U8LwiLGINgBULm5gZNmCsYZ5VftNjy9+9nZv9xhZOc1mdptluAu542S2RUBkBF\reL5SJ1pAtrWRp4XveauJUwfvq+jsW9WTbW0WKTKEST2MX3slUHdif0Cx49MjOiUf\rOjo/C1UMrxIjYfTiZjLycFJVH8HcNql8DSKcg0vu7GzY8S/98ZXuFcyEDxJzpiV0\rp5uCoq3cRA7+/KnBGHBgs5Tf8yQgi7ulPA2vliHz4GHdM6dGCG6UvA/gd7lMqxbq\r1CGi3qUbuDRSJL2lHzTwH0yRUxoVY4tBC8nwEzoVAg0CgYEA/CdtrGyC8DOD80F1\rdq8wsPalf6yL2S58LJ7cRUe5Nf/oog+2KWZ/j6B/Feps75NV1lgI1EKs150B9so6\rNJFPZScxceUC99B09rVcOnI4gV+TO3I9gwMGUmB7GUlAhAuUB42NaXUMAYFCOQOA\r2NGBKrq+FTDjaXBs6lhwfJNOIeMCgYEAyisVIPRhR/Q72bIWJmYhfMDCWv79iZqq\rHijAcLTZ89AsGO6zZ6d1GR+V4jZVtA4d+LTS875pYPhHD8hMzAn/zp6H8WuOyyn9\r4baMKOGz0QWFrjlK5Y+yWnYbr5awjtccOSTT3UDtkrtqkNG6eu8iiK5mbts8N1RC\r1j71a5LJ97sCgYEAldRf6Nq5mz0hJMQ6pgFHb3+/q3O9zZk/k8v5mvkZZqrfcpzf\rYw5SseduXHllrZ3gnXLGHEpaJexXpGtZ1q6ZfMOjL8gi0Vn+hjIR0XDZfpZqCCLD\rxjtf4EcQHmBWg5/Vn/9OjeFM9v/1d6dLQoqKs/cux6y7FIYHUeCnRn7JKH0CgYB3\ruiP9LD0ge8emGQ19GCbk1tNDSJemEm6FBeVR2gjpl3NGILcmv8ldY5NEMKF4zJN7\rYrs7lpyZzO9orVqty44vMzuXAffC4c91CMLgwynWs8qDb3KnmP4rDJ9A0aEmNsaE\rIQdHlNgdediWg15Ix65P+9i19ignLEOY1hhJ6NirWQKBgC0KYNdoJ6JXnOjNBKPl\rRO4z9Gan6CqYqfGAL2AGVPyJQEkW4x0R3q8Yqr7IBckGCN3fAZDVfsK/gTfIji8x\rCF4YH6jIdk4IjM3cU+8XW4ibWisccV+EzbSh+kPMYEYz0t/WzFKvs/AcdcfiNDVo\r+NEF0Z1FUmIHjzPmNmMd1DBa\r"
a=0;// 
a=0;//     #v2=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v0}, Lcom/wukongtv/a/e;->a(Ljava/lang/String;)[B
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v2}, Lcom/wukongtv/a/e;->a(Ljava/lang/String;)[B
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     const-string v3, "RSA"
a=0;// 
a=0;//     #v3=(Reference,Ljava/lang/String;);
a=0;//     invoke-static {v3}, Ljava/security/KeyFactory;->getInstance(Ljava/lang/String;)Ljava/security/KeyFactory;
a=0;// 
a=0;//     move-result-object v3
a=0;// 
a=0;//     new-instance v4, Ljava/security/spec/PKCS8EncodedKeySpec;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/security/spec/PKCS8EncodedKeySpec;);
a=0;//     invoke-direct {v4, v2}, Ljava/security/spec/PKCS8EncodedKeySpec;-><init>([B)V
a=0;// 
a=0;//     #v4=(Reference,Ljava/security/spec/PKCS8EncodedKeySpec;);
a=0;//     invoke-virtual {v3, v4}, Ljava/security/KeyFactory;->generatePrivate(Ljava/security/spec/KeySpec;)Ljava/security/PrivateKey;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     new-instance v4, Ljava/security/spec/X509EncodedKeySpec;
a=0;// 
a=0;//     #v4=(UninitRef,Ljava/security/spec/X509EncodedKeySpec;);
a=0;//     invoke-direct {v4, v0}, Ljava/security/spec/X509EncodedKeySpec;-><init>([B)V
a=0;// 
a=0;//     #v4=(Reference,Ljava/security/spec/X509EncodedKeySpec;);
a=0;//     invoke-virtual {v3, v4}, Ljava/security/KeyFactory;->generatePublic(Ljava/security/spec/KeySpec;)Ljava/security/PublicKey;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v3, "public"
a=0;// 
a=0;//     invoke-virtual {v1, v3, v0}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;// 
a=0;//     const-string v0, "private"
a=0;// 
a=0;//     invoke-virtual {v1, v0, v2}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
a=0;//     :try_end_0
a=0;//     .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0
a=0;// 
a=0;//     :goto_0
a=0;//     #v3=(Conflicted);v4=(Conflicted);
a=0;//     return-object v1
a=0;// 
a=0;//     :catch_0
a=0;//     #v0=(Conflicted);v2=(Conflicted);
a=0;//     move-exception v0
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/Exception;);
a=0;//     sget-object v2, Ljava/lang/System;->err:Ljava/io/PrintStream;
a=0;// 
a=0;//     #v2=(Reference,Ljava/io/PrintStream;);
a=0;//     invoke-virtual {v2, v0}, Ljava/io/PrintStream;->println(Ljava/lang/Object;)V
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
}}
