package android.support.v4.widget; class n { void a() { int a;
a=0;// .class final Landroid/support/v4/widget/n;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public static a(Ljava/lang/Object;II)V
a=0;//     .locals 0
a=0;// 
a=0;//     check-cast p0, Landroid/widget/EdgeEffect;
a=0;// 
a=0;//     invoke-virtual {p0, p1, p2}, Landroid/widget/EdgeEffect;->setSize(II)V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static a(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;// 
a=0;//     check-cast p0, Landroid/widget/EdgeEffect;
a=0;// 
a=0;//     invoke-virtual {p0}, Landroid/widget/EdgeEffect;->isFinished()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static a(Ljava/lang/Object;F)Z
a=0;//     .locals 1
a=0;// 
a=0;//     check-cast p0, Landroid/widget/EdgeEffect;
a=0;// 
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/EdgeEffect;->onPull(F)V
a=0;// 
a=0;//     const/4 v0, 0x1
a=0;// 
a=0;//     #v0=(One);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static a(Ljava/lang/Object;Landroid/graphics/Canvas;)Z
a=0;//     .locals 1
a=0;// 
a=0;//     check-cast p0, Landroid/widget/EdgeEffect;
a=0;// 
a=0;//     invoke-virtual {p0, p1}, Landroid/widget/EdgeEffect;->draw(Landroid/graphics/Canvas;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public static b(Ljava/lang/Object;)V
a=0;//     .locals 0
a=0;// 
a=0;//     check-cast p0, Landroid/widget/EdgeEffect;
a=0;// 
a=0;//     invoke-virtual {p0}, Landroid/widget/EdgeEffect;->finish()V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public static c(Ljava/lang/Object;)Z
a=0;//     .locals 1
a=0;// 
a=0;//     check-cast p0, Landroid/widget/EdgeEffect;
a=0;// 
a=0;//     invoke-virtual {p0}, Landroid/widget/EdgeEffect;->onRelease()V
a=0;// 
a=0;//     invoke-virtual {p0}, Landroid/widget/EdgeEffect;->isFinished()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     return v0
a=0;// .end method
}}
