package a.a; class da { void a() { int a;
a=0;// .class final La/a/da;
a=0;// .super La/a/gf;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method private constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-direct {p0}, La/a/gf;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,La/a/da;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method synthetic constructor <init>(B)V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-direct {p0}, La/a/da;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,La/a/da;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final synthetic a(La/a/fu;La/a/eu;)V
a=0;//     .locals 1
a=0;// 
a=0;//     check-cast p2, La/a/cx;
a=0;// 
a=0;//     check-cast p1, La/a/gb;
a=0;// 
a=0;//     invoke-virtual {p1}, La/a/gb;->m()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     iput v0, p2, La/a/cx;->a:I
a=0;// 
a=0;//     invoke-virtual {p2}, La/a/cx;->a()V
a=0;// 
a=0;//     invoke-virtual {p1}, La/a/gb;->m()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     iput v0, p2, La/a/cx;->b:I
a=0;// 
a=0;//     invoke-virtual {p2}, La/a/cx;->b()V
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public final synthetic b(La/a/fu;La/a/eu;)V
a=0;//     .locals 1
a=0;// 
a=0;//     check-cast p2, La/a/cx;
a=0;// 
a=0;//     check-cast p1, La/a/gb;
a=0;// 
a=0;//     iget v0, p2, La/a/cx;->a:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-virtual {p1, v0}, La/a/gb;->a(I)V
a=0;// 
a=0;//     iget v0, p2, La/a/cx;->b:I
a=0;// 
a=0;//     invoke-virtual {p1, v0}, La/a/gb;->a(I)V
a=0;// 
a=0;//     return-void
a=0;// .end method
}}
