package a.b; class k { void a() { int a;
a=0;// .class public abstract La/b/k;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # static fields
a=0;// .field protected static b:Ljava/lang/String;
a=0;// 
a=0;// .field public static c:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field public d:Ljava/lang/String;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method static constructor <clinit>()V
a=0;//     .locals 1
a=0;// 
a=0;//     const-string v0, "POST"
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     sput-object v0, La/b/k;->b:Ljava/lang/String;
a=0;// 
a=0;//     const-string v0, "GET"
a=0;// 
a=0;//     sput-object v0, La/b/k;->c:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,La/b/k;);
a=0;//     iput-object p1, p0, La/b/k;->d:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public a(Ljava/lang/String;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, La/b/k;->d:Ljava/lang/String;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public b()Ljava/lang/String;
a=0;//     .locals 1
a=0;// 
a=0;//     sget-object v0, La/b/k;->b:Ljava/lang/String;
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/String;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public abstract c()Lorg/json/JSONObject;
a=0;// .end method
a=0;// 
a=0;// .method public abstract d()Ljava/lang/String;
a=0;// .end method
}}
