package com.b.a.a; class ac { void a() { int a;
a=0;// .class public interface abstract Lcom/b/a/a/ac;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract a(I)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract a(Ljava/net/URI;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract a(Lorg/apache/http/HttpResponse;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract a([Lorg/apache/http/Header;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract a()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract b(II)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract b(I[Lorg/apache/http/Header;[BLjava/lang/Throwable;)V
a=0;// .end method
a=0;// 
a=0;// .method public abstract d()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract e()V
a=0;// .end method
a=0;// 
a=0;// .method public abstract f()V
a=0;// .end method
}}
