package com.lovesport.fitCommon; class x { void a() { int a;
a=0;// .class final Lcom/lovesport/fitCommon/x;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/media/MediaPlayer$OnCompletionListener;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/lovesport/fitCommon/WukongVideoView;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcom/lovesport/fitCommon/x;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/lovesport/fitCommon/x;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final onCompletion(Landroid/media/MediaPlayer;)V
a=0;//     .locals 2
a=0;// 
a=0;//     const/4 v1, 0x5
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/x;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     #v0=(Reference,Lcom/lovesport/fitCommon/WukongVideoView;);
a=0;//     invoke-static {v0, v1}, Lcom/lovesport/fitCommon/WukongVideoView;->c(Lcom/lovesport/fitCommon/WukongVideoView;I)I
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/x;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/lovesport/fitCommon/WukongVideoView;->d(Lcom/lovesport/fitCommon/WukongVideoView;I)I
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/x;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->c(Lcom/lovesport/fitCommon/WukongVideoView;)Lcom/lovesport/fitCommon/p;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/x;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->c(Lcom/lovesport/fitCommon/WukongVideoView;)Lcom/lovesport/fitCommon/p;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/lovesport/fitCommon/p;->a()V
a=0;// 
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/x;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->d(Lcom/lovesport/fitCommon/WukongVideoView;)Landroid/media/MediaPlayer$OnCompletionListener;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/x;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->d(Lcom/lovesport/fitCommon/WukongVideoView;)Landroid/media/MediaPlayer$OnCompletionListener;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/lovesport/fitCommon/x;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     #v1=(Reference,Lcom/lovesport/fitCommon/WukongVideoView;);
a=0;//     invoke-static {v1}, Lcom/lovesport/fitCommon/WukongVideoView;->e(Lcom/lovesport/fitCommon/WukongVideoView;)Landroid/media/MediaPlayer;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-interface {v0, v1}, Landroid/media/MediaPlayer$OnCompletionListener;->onCompletion(Landroid/media/MediaPlayer;)V
a=0;// 
a=0;//     :cond_1
a=0;//     #v1=(Conflicted);
a=0;//     return-void
a=0;// .end method
}}
