package com.lovesport.fitCommon; class z { void a() { int a;
a=0;// .class final Lcom/lovesport/fitCommon/z;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/media/MediaPlayer$OnErrorListener;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field final synthetic a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>(Lcom/lovesport/fitCommon/WukongVideoView;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/lovesport/fitCommon/z;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final onError(Landroid/media/MediaPlayer;II)Z
a=0;//     .locals 4
a=0;// 
a=0;//     const/4 v3, 0x1
a=0;// 
a=0;//     #v3=(One);
a=0;//     const/4 v2, -0x1
a=0;// 
a=0;//     #v2=(Byte);
a=0;//     new-instance v0, Ljava/lang/StringBuilder;
a=0;// 
a=0;//     #v0=(UninitRef,Ljava/lang/StringBuilder;);
a=0;//     const-string v1, "Error: "
a=0;// 
a=0;//     #v1=(Reference,Ljava/lang/String;);
a=0;//     invoke-direct {v0, v1}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V
a=0;// 
a=0;//     #v0=(Reference,Ljava/lang/StringBuilder;);
a=0;//     invoke-virtual {v0, p2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, ","
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, p3}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0, v2}, Lcom/lovesport/fitCommon/WukongVideoView;->c(Lcom/lovesport/fitCommon/WukongVideoView;I)I
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0, v2}, Lcom/lovesport/fitCommon/WukongVideoView;->d(Lcom/lovesport/fitCommon/WukongVideoView;I)I
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->c(Lcom/lovesport/fitCommon/WukongVideoView;)Lcom/lovesport/fitCommon/p;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->c(Lcom/lovesport/fitCommon/WukongVideoView;)Lcom/lovesport/fitCommon/p;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/lovesport/fitCommon/p;->a()V
a=0;// 
a=0;//     :cond_0
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->f(Lcom/lovesport/fitCommon/WukongVideoView;)Landroid/media/MediaPlayer$OnErrorListener;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_2
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->f(Lcom/lovesport/fitCommon/WukongVideoView;)Landroid/media/MediaPlayer$OnErrorListener;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/lovesport/fitCommon/WukongVideoView;->e(Lcom/lovesport/fitCommon/WukongVideoView;)Landroid/media/MediaPlayer;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-interface {v0, v1, p2, p3}, Landroid/media/MediaPlayer$OnErrorListener;->onError(Landroid/media/MediaPlayer;II)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_2
a=0;// 
a=0;//     :cond_1
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);
a=0;//     return v3
a=0;// 
a=0;//     :cond_2
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     #v0=(Reference,Lcom/lovesport/fitCommon/WukongVideoView;);
a=0;//     invoke-virtual {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->getWindowToken()Landroid/os/IBinder;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     iget-object v0, p0, Lcom/lovesport/fitCommon/z;->a:Lcom/lovesport/fitCommon/WukongVideoView;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/fitCommon/WukongVideoView;->g(Lcom/lovesport/fitCommon/WukongVideoView;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Landroid/content/Context;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     goto :goto_0
a=0;// .end method
}}
