package com.alimama.mobile.csdk.umupdate.a; class a { void a() { int a;
a=0;// .class public interface abstract Lcom/alimama/mobile/csdk/umupdate/a/a;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public abstract a()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract a(Ljava/lang/String;)Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract b()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract b(Ljava/lang/String;)Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract c()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract d()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract e()Z
a=0;// .end method
a=0;// 
a=0;// .method public abstract f()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract g()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract h()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract i()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract j()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract k()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract l()[Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract m()Landroid/location/Location;
a=0;// .end method
a=0;// 
a=0;// .method public abstract n()Ljava/lang/String;
a=0;// .end method
a=0;// 
a=0;// .method public abstract o()Ljava/lang/String;
a=0;// .end method
}}
