package com.wukongtv.wkhelper.d; class f { void a() { int a;
a=0;// .class final Lcom/wukongtv/wkhelper/d/f;
a=0;// .super Ljava/lang/Object;
a=0;// 
a=0;// # interfaces
a=0;// .implements Ljava/lang/Runnable;
a=0;// 
a=0;// 
a=0;// # instance fields
a=0;// .field a:Lcom/wukongtv/wkhelper/d/g;
a=0;// 
a=0;// .field final synthetic b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Lcom/wukongtv/wkhelper/d/a;Lcom/wukongtv/wkhelper/d/g;)V
a=0;//     .locals 0
a=0;// 
a=0;//     iput-object p1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Lcom/wukongtv/wkhelper/d/f;);
a=0;//     iput-object p2, p0, Lcom/wukongtv/wkhelper/d/f;->a:Lcom/wukongtv/wkhelper/d/g;
a=0;// 
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public final run()V
a=0;//     .locals 5
a=0;//     .annotation build Landroid/annotation/SuppressLint;
a=0;//         value = {
a=0;//             "InflateParams"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     const/4 v3, 0x0
a=0;// 
a=0;//     #v3=(Null);
a=0;//     const/4 v4, 0x0
a=0;// 
a=0;//     #v4=(Null);
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->a:Lcom/wukongtv/wkhelper/d/g;
a=0;// 
a=0;//     #v0=(Reference,Lcom/wukongtv/wkhelper/d/g;);
a=0;//     iget-object v0, v0, Lcom/wukongtv/wkhelper/d/g;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-static {v0}, Landroid/text/TextUtils;->isEmpty(Ljava/lang/CharSequence;)Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-eqz v0, :cond_1
a=0;// 
a=0;//     :cond_0
a=0;//     :goto_0
a=0;//     #v0=(Conflicted);v1=(Conflicted);v2=(Conflicted);v3=(Integer);
a=0;//     return-void
a=0;// 
a=0;//     :cond_1
a=0;//     #v0=(Boolean);v1=(Uninit);v2=(Uninit);v3=(Null);
a=0;//     new-instance v0, Lcom/wukongtv/wkhelper/d/e;
a=0;// 
a=0;//     #v0=(UninitRef,Lcom/wukongtv/wkhelper/d/e;);
a=0;//     iget-object v1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     #v1=(Reference,Lcom/wukongtv/wkhelper/d/a;);
a=0;//     iget-object v2, p0, Lcom/wukongtv/wkhelper/d/f;->a:Lcom/wukongtv/wkhelper/d/g;
a=0;// 
a=0;//     #v2=(Reference,Lcom/wukongtv/wkhelper/d/g;);
a=0;//     invoke-direct {v0, v1, v2}, Lcom/wukongtv/wkhelper/d/e;-><init>(Lcom/wukongtv/wkhelper/d/a;Lcom/wukongtv/wkhelper/d/g;)V
a=0;// 
a=0;//     #v0=(Reference,Lcom/wukongtv/wkhelper/d/e;);
a=0;//     iget-object v1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/wukongtv/wkhelper/d/a;->h(Lcom/wukongtv/wkhelper/d/a;)Lcom/b/a/a/b;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iget-object v2, p0, Lcom/wukongtv/wkhelper/d/f;->a:Lcom/wukongtv/wkhelper/d/g;
a=0;// 
a=0;//     iget-object v2, v2, Lcom/wukongtv/wkhelper/d/g;->b:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v1, v2, v3, v0}, Lcom/b/a/a/b;->a(Ljava/lang/String;Lcom/b/a/a/z;Lcom/b/a/a/ac;)Lcom/b/a/a/y;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     if-nez v0, :cond_2
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->d(Lcom/wukongtv/wkhelper/d/a;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const-string v1, "layout_inflater"
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/content/Context;->getSystemService(Ljava/lang/String;)Ljava/lang/Object;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/view/LayoutInflater;
a=0;// 
a=0;//     const v1, 0x7f030012
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1, v3, v4}, Landroid/view/LayoutInflater;->inflate(ILandroid/view/ViewGroup;Z)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     #v1=(Reference,Lcom/wukongtv/wkhelper/d/a;);
a=0;//     iget-object v2, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/wukongtv/wkhelper/d/a;->d(Lcom/wukongtv/wkhelper/d/a;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     sget v3, Lcom/a/a/a/c;->b:I
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-static {v2, v0, v4, v3}, Lcom/a/a/a/b;->a(Landroid/content/Context;Landroid/view/View;II)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-static {v1, v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;Lcom/a/a/a/b;)Lcom/a/a/a/b;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/a/a/a/b;->b()Lcom/a/a/a/b;
a=0;// 
a=0;//     :cond_2
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->i(Lcom/wukongtv/wkhelper/d/a;)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     new-instance v2, Lcom/wukongtv/wkhelper/d/k;
a=0;// 
a=0;//     #v2=(UninitRef,Lcom/wukongtv/wkhelper/d/k;);
a=0;//     iget-object v3, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     #v3=(Reference,Lcom/wukongtv/wkhelper/d/a;);
a=0;//     invoke-direct {v2, v3, v4}, Lcom/wukongtv/wkhelper/d/k;-><init>(Lcom/wukongtv/wkhelper/d/a;B)V
a=0;// 
a=0;//     #v2=(Reference,Lcom/wukongtv/wkhelper/d/k;);
a=0;//     invoke-static {v0, v2}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;Lcom/wukongtv/wkhelper/d/k;)Lcom/wukongtv/wkhelper/d/k;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/a/a/a/b;->c:Landroid/view/View;
a=0;// 
a=0;//     const v2, 0x7f0b004a
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v0, v2}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/widget/TextView;
a=0;// 
a=0;//     iget-object v2, p0, Lcom/wukongtv/wkhelper/d/f;->a:Lcom/wukongtv/wkhelper/d/g;
a=0;// 
a=0;//     #v2=(Reference,Lcom/wukongtv/wkhelper/d/g;);
a=0;//     iget-object v2, v2, Lcom/wukongtv/wkhelper/d/g;->d:Ljava/lang/String;
a=0;// 
a=0;//     invoke-virtual {v0, v2}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     iget-object v2, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v2}, Lcom/wukongtv/wkhelper/d/a;->j(Lcom/wukongtv/wkhelper/d/a;)Lcom/wukongtv/wkhelper/d/k;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iput-object v0, v2, Lcom/wukongtv/wkhelper/d/k;->a:Landroid/widget/TextView;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->j(Lcom/wukongtv/wkhelper/d/a;)Lcom/wukongtv/wkhelper/d/k;
a=0;// 
a=0;//     move-result-object v2
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/a/a/a/b;->c:Landroid/view/View;
a=0;// 
a=0;//     const v3, 0x7f0b004c
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-virtual {v0, v3}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/widget/TextView;
a=0;// 
a=0;//     iput-object v0, v2, Lcom/wukongtv/wkhelper/d/k;->c:Landroid/widget/TextView;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->j(Lcom/wukongtv/wkhelper/d/a;)Lcom/wukongtv/wkhelper/d/k;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/wukongtv/wkhelper/d/k;->c:Landroid/widget/TextView;
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/TextView;->setVisibility(I)V
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0, v1}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;I)V
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/a/a/a/b;->c:Landroid/view/View;
a=0;// 
a=0;//     const v1, 0x7f0b004b
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/widget/TextView;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     #v1=(Reference,Lcom/wukongtv/wkhelper/d/a;);
a=0;//     invoke-static {v1}, Lcom/wukongtv/wkhelper/d/a;->d(Lcom/wukongtv/wkhelper/d/a;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v1}, Landroid/content/Context;->getResources()Landroid/content/res/Resources;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const v2, 0x7f09000b
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-virtual {v1, v2}, Landroid/content/res/Resources;->getColor(I)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setTextColor(I)V
a=0;// 
a=0;//     iget-object v1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     #v1=(Reference,Lcom/wukongtv/wkhelper/d/a;);
a=0;//     invoke-static {v1}, Lcom/wukongtv/wkhelper/d/a;->d(Lcom/wukongtv/wkhelper/d/a;)Landroid/content/Context;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     const v2, 0x7f070085
a=0;// 
a=0;//     invoke-virtual {v1, v2}, Landroid/content/Context;->getString(I)Ljava/lang/String;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/TextView;->setText(Ljava/lang/CharSequence;)V
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/TextView;->setVisibility(I)V
a=0;// 
a=0;//     iget-object v1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v1}, Lcom/wukongtv/wkhelper/d/a;->j(Lcom/wukongtv/wkhelper/d/a;)Lcom/wukongtv/wkhelper/d/k;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iput-object v0, v1, Lcom/wukongtv/wkhelper/d/k;->b:Landroid/widget/TextView;
a=0;// 
a=0;//     iget-object v1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v0, v0, Lcom/a/a/a/b;->c:Landroid/view/View;
a=0;// 
a=0;//     const v2, 0x7f0b004d
a=0;// 
a=0;//     invoke-virtual {v0, v2}, Landroid/view/View;->findViewById(I)Landroid/view/View;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     check-cast v0, Landroid/widget/ProgressBar;
a=0;// 
a=0;//     invoke-static {v1, v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;Landroid/widget/ProgressBar;)Landroid/widget/ProgressBar;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->g(Lcom/wukongtv/wkhelper/d/a;)Landroid/widget/ProgressBar;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/ProgressBar;->setVisibility(I)V
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->g(Lcom/wukongtv/wkhelper/d/a;)Landroid/widget/ProgressBar;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     const/16 v1, 0x64
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     invoke-virtual {v0, v1}, Landroid/widget/ProgressBar;->setMax(I)V
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->g(Lcom/wukongtv/wkhelper/d/a;)Landroid/widget/ProgressBar;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0, v4}, Landroid/widget/ProgressBar;->setProgress(I)V
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->j(Lcom/wukongtv/wkhelper/d/a;)Lcom/wukongtv/wkhelper/d/k;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     iget-object v1, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     #v1=(Reference,Lcom/wukongtv/wkhelper/d/a;);
a=0;//     invoke-static {v1}, Lcom/wukongtv/wkhelper/d/a;->g(Lcom/wukongtv/wkhelper/d/a;)Landroid/widget/ProgressBar;
a=0;// 
a=0;//     move-result-object v1
a=0;// 
a=0;//     iput-object v1, v0, Lcom/wukongtv/wkhelper/d/k;->d:Landroid/widget/ProgressBar;
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/a/a/a/b;->d()Z
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Boolean);
a=0;//     if-nez v0, :cond_0
a=0;// 
a=0;//     iget-object v0, p0, Lcom/wukongtv/wkhelper/d/f;->b:Lcom/wukongtv/wkhelper/d/a;
a=0;// 
a=0;//     #v0=(Reference,Lcom/wukongtv/wkhelper/d/a;);
a=0;//     invoke-static {v0}, Lcom/wukongtv/wkhelper/d/a;->a(Lcom/wukongtv/wkhelper/d/a;)Lcom/a/a/a/b;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     invoke-virtual {v0}, Lcom/a/a/a/b;->a()V
a=0;// 
a=0;//     goto/16 :goto_0
a=0;// .end method
}}
