package com.lovesport.lc; class AutoView { void a() { int a;
a=0;// .class public Lcom/lovesport/lc/AutoView;
a=0;// .super Landroid/view/View;
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method public constructor <init>(Landroid/content/Context;)V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-direct {p0, p1}, Landroid/view/View;-><init>(Landroid/content/Context;)V
a=0;// 
a=0;//     #p0=(Reference,Lcom/lovesport/lc/AutoView;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;)V
a=0;//     .locals 0
a=0;// 
a=0;//     invoke-direct {p0, p1, p2}, Landroid/view/View;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V
a=0;// 
a=0;//     #p0=(Reference,Lcom/lovesport/lc/AutoView;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public constructor <init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V
a=0;//     .locals 4
a=0;//     .annotation build Landroid/annotation/SuppressLint;
a=0;//         value = {
a=0;//             "NewApi"
a=0;//         }
a=0;//     .end annotation
a=0;// 
a=0;//     invoke-direct {p0, p1, p2, p3}, Landroid/view/View;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;I)V
a=0;// 
a=0;//     #p0=(Reference,Lcom/lovesport/lc/AutoView;);
a=0;//     invoke-static {p0}, Lcom/lovesport/lc/a;->a(Landroid/view/View;)V
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getPaddingLeft()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(I)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getPaddingTop()I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     #v1=(Integer);
a=0;//     invoke-static {v1}, Lcom/lovesport/lc/a;->a(I)I
a=0;// 
a=0;//     move-result v1
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getPaddingRight()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     invoke-static {v2}, Lcom/lovesport/lc/a;->a(I)I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getPaddingBottom()I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     #v3=(Integer);
a=0;//     invoke-static {v3}, Lcom/lovesport/lc/a;->a(I)I
a=0;// 
a=0;//     move-result v3
a=0;// 
a=0;//     invoke-virtual {p0, v0, v1, v2, v3}, Lcom/lovesport/lc/AutoView;->setPadding(IIII)V
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getScaleX()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(F)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setScaleX(F)V
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getScaleY()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(F)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setScaleY(F)V
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getTranslationX()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(F)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setPivotX(F)V
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getTranslationY()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(F)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setPivotY(F)V
a=0;// 
a=0;//     sget v0, Landroid/os/Build$VERSION;->SDK_INT:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/16 v1, 0xe
a=0;// 
a=0;//     #v1=(PosByte);
a=0;//     if-lt v0, v1, :cond_0
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getScrollX()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(I)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setScrollX(I)V
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getScrollY()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(I)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setScrollY(I)V
a=0;// 
a=0;//     :cond_0
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getTranslationX()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(F)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setTranslationX(F)V
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getTranslationY()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(F)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setTranslationY(F)V
a=0;// 
a=0;//     sget v0, Landroid/os/Build$VERSION;->SDK_INT:I
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     const/16 v1, 0x15
a=0;// 
a=0;//     if-lt v0, v1, :cond_1
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getTranslationZ()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Float);
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(F)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setTranslationZ(F)V
a=0;// 
a=0;//     invoke-virtual {p0}, Lcom/lovesport/lc/AutoView;->getElevation()F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-static {v0}, Lcom/lovesport/lc/a;->a(F)F
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     invoke-virtual {p0, v0}, Lcom/lovesport/lc/AutoView;->setElevation(F)V
a=0;// 
a=0;//     :cond_1
a=0;//     #v0=(Integer);
a=0;//     return-void
a=0;// .end method
}}
